### ISSUE TITLE
`sa_index` error

### ISSUE THREAD

**Issue by omaru-ok** [jsmsj/GdriveCloneBot#3]
tried to pubclone gettign sa_index error 

eveerythign is fine , also 
authsa ✅  
auth ✅ 
list-project ✅ 

only pubclone not workign :(

![image](https://user-images.githubusercontent.com/108952834/212056912-5579c913-9535-4554-9a79-aa394ffbad2f.png)

**Comment by jsmsj** [comment]
Fixed it in repo, 

just replace `sa_index +=1` by `self.sa_index+=1` in [https://github.com/jsmsj/GdriveCloneBot/blob/17b34b6fed6d13c1dea7f23448c85a27e5324138/cogs/_gd_utils.py#L234](this file)
and take care of the indentation

**Comment by omaru-ok** [comment]
seems to work fine
